#!/usr/bin/env bash

set -e  # Exit immediately if a command exits with a non-zero status.

# Activate the environment generated by install.sh.
# shellcheck disable=SC1091
source .env/bin/activate

# Download the test data.
gdown https://raw.githubusercontent.com/YosefLab/Compass/refs/heads/master/compass/Resources/Test-Data/tsv_format/expression.tsv

# Run Compass.
compass --num-thread 32 --data expression.tsv --species homo_sapiens

# Clean up.
rm expression.tsv
rm model.json.gz
rm reactions.tsv
