[package]
edition = "2021"
name = "compass"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blas-src.workspace = true
clap.workspace = true
ndarray.workspace = true
openblas-src.workspace = true
polars.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

# Intra-workspace dependencies
cplex-bindings.workspace = true
gsmm.workspace = true
