[workspace]
members = ["cplex-bindings", "compass", "cplex-rs"]

resolver = "2"

[workspace.dependencies]
bindgen = { version = "0.70" }

# Intra-workspace dependencies
cplex-bindings = { path = "cplex-bindings" }
