[workspace]
members = ["compass", "cplex-bindings", "cplex-rs", "gsmm"]

resolver = "2"

[workspace.dependencies]
bindgen = { version = "0.70" }
clap = { version = "4.5", features = ["derive"] }
itertools = { version = "0.13" }
ndarray = { version = "0.16", features = ["blas", "serde"] }
polars = { version = "0.45", features = ["lazy", "strings"] }
regex = { version = "1.11" }
rust_sbml = { version = "0.7", default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }

# Note that the following blas libraries are only intended for executables to chose.
blas-src = { version = "0.10", features = ["openblas"] }
openblas-src = { version = "0.10", features = ["system"] }

# Intra-workspace dependencies
cplex-bindings = { path = "cplex-bindings" }
gsmm = { path = "gsmm" }
